-- find no pk table

SELECT i.TABLE_ID, t.NAME  
FROM INFORMATION_SCHEMA.INNODB_INDEXES i  
   JOIN INFORMATION_SCHEMA.INNODB_TABLES t ON (i.TABLE_ID = t.TABLE_ID)  
WHERE      i.NAME='GEN_CLUST_INDEX';
